#!/usr/bin/env bash
# Crop the tile maps. For definitions of such tiles, refer to src/main/scala/TileMap.scala.
# See README.md for how to download maps.

mapdir=../res/drawable
tile=256

# Parameter set for Blue Marble map
file=land_shallow_topo_east.tif

# Parameters to crop the map we need.
lon=35
lat=16
west=6836
north=5000

# Command line options for ImageMagick to lift the resource limitations.
convert $file -crop $((lon*tile))x$((lat*tile))+${west}+${north} china.png

for (( i=0; i<$lon; i++ ))
do
    for (( j=0; j<$lat; j++ ))
    do
        convert china.png -crop ${tile}x${tile}+$((west+i*tile))+$((north+j*tile)) $mapdir/map_0_${i}_${j}.png
    done
done
